<?php
// set the format of the flash messenger output to work for the Twitter Bootstrap theme.
$this->flashMessenger()
     ->setMessageOpenFormat(
        '<div%s>
        <button type="button" class="close" data-dismiss="alert"
            aria-hidden="true">&times;
        </button><ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');
?>
<?php if ($this->messages['info']): ?>
<?php echo $this->flashMessenger()->render('info', array('alert', 'alert-dismissable', 'alert-info')); ?>
<?php endif; ?>