<h1 class="page-header"><?php echo $this->translate('Feeds Dashboard'); ?></h1>

<ul class="breadcrumb">
    <li><a href="/">Home</a>
    <li><a href="<?php print $this->url('feeds'); ?>">Feeds</a></li>
    <li class="active">All Feeds</li>
</ul>

<?php echo $this->partial('babymonitor/feeds/messages/default'); ?>

<?php if (count($this->paginator)) : ?>
<p>Here are the last <?php print $feedCount; ?> feeds, from latest to oldest.</p>
<?php endif; ?>

<?php echo $this->partial('babymonitor/feeds/results/search/default', array(
    'paginator' => $this->paginator
)); ?>