<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="masthead clearfix">
                <div class="inner">
                    <h3 class="masthead-brand">ZF2 For Beginners</h3>
                    <ul class="nav masthead-nav">
                        <li><a href="https://leanpub.com/zendframework2-for-beginners"
                               target="_blank">Buy The Book</a></li>
                        <li><a href="https://github.com/settermjd/zf2forbeginners"
                               title="Come find out about ZF2 for Beginners on Github"
                               target="_blank">On Github</a></li>
                        <li><a href="<?php print $this->url('feeds', array()); ?>">Feeds Dashboard</a></li>
                    </ul>
                </div>
            </div>

            <div class="inner cover">
                <h1 class="cover-heading">Hey There!</h1>
                <p class="lead">
                    This codebase and the accompanying book, <a href="https://leanpub.com/zendframework2-for-beginners"
                    target="_blank">ZF2 For Beginners</a>, is all about showing beginners how to get the most out of
                    Zend Framework 2. Feel free to review and experiment with the code, as you're working through the
                book so that you get the most out of the experience.</p>
                <p class="lead">
                    <a href="https://leanpub.com/zendframework2-for-beginners" target="_blank"
                       class="btn btn-lg btn-default">Learn more</a>
                </p>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>,
                        by <a href="https://twitter.com/mdo">@mdo</a>,
                        revised by <a href="https://twitter.com/settermjd">@settermjd</a></p>
                    <p>copyright &copy; Matthew Setter. All rights reserved.</p>
                </div>
            </div>

        </div>

    </div>

</div>